development:
  adapter: postgresql
  encoding: unicode
  database: nom_nom_development
  pool: 5
  username: nom_nom
  password: nom_nom
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: nom_nom_test
  pool: 5
  username: nom_nom
  password: nom_nom
production:
  adapter: postgresql
  encoding: unicode
  database: nom_nom_production
  pool: 5
  username: nom_nom
  password: nom_nom